#!/bin/bash

echo "🔧 Fixing World Object Visibility in RViz"
echo "=========================================="

echo "Based on your screenshot, I can see the topics exist but objects aren't visible."
echo "This is likely an RViz display configuration issue."
echo ""

echo "🔍 **Manual Fix Steps:**"
echo ""
echo "1. **In RViz Displays Panel (left side):**"
echo "   • Look for 'World_Environment' and 'Interactive_Objects'"
echo "   • Make sure they have GREEN checkmarks ✅"
echo "   • If they have RED X marks ❌, click on them"
echo ""
echo "2. **Check Topic Settings:**"
echo "   • Expand 'World_Environment' in displays"
echo "   • Check 'Topic' field shows: /world_environment"
echo "   • Expand 'Interactive_Objects' in displays"
echo "   • Check 'Topic' field shows: /interactive_objects"
echo ""
echo "3. **Force Refresh:**"
echo "   • Uncheck the displays (turn them off)"
echo "   • Wait 2 seconds"
echo "   • Check them again (turn them on)"
echo ""
echo "4. **Check Fixed Frame:**"
echo "   • In Global Options, Fixed Frame should be 'base_link'"
echo "   • If it shows something else, change it to 'base_link'"
echo ""
echo "5. **Zoom and Position:**"
echo "   • Scroll mouse wheel to zoom out"
echo "   • Look around - objects might be outside view"
echo ""

echo "🧪 **Let's test with a simple manual command:**"
echo ""
echo "In a new terminal, run this command to publish a test object:"
echo ""
echo "ros2 topic pub --once /manual_test_marker visualization_msgs/msg/MarkerArray \\"
echo "'{markers: [{header: {frame_id: \"base_link\"}, ns: \"test\", id: 1, type: 1, action: 0, pose: {position: {x: 1.0, y: 0.0, z: 0.5}, orientation: {w: 1.0}}, scale: {x: 0.5, y: 0.5, z: 0.5}, color: {r: 1.0, g: 0.0, b: 0.0, a: 1.0}}]}'"
echo ""
echo "Then in RViz:"
echo "• Add → By topic → /manual_test_marker → MarkerArray"
echo "• You should see a red cube"
echo ""

echo "🎯 **If objects still don't show:**"
echo "• The issue is with RViz MarkerArray display"
echo "• We can switch to using TF frames or other visualization methods"
echo ""

echo "Press ENTER to continue..."
read

echo "✅ Instructions provided. Try the manual steps above!"